[versions]
lamp = "4.0.0-rc.14"
adventure = "4.20.0"
packetevents = "2.10.0"

[libraries]
passport = { group = "me.combimagnetron", name = "Passport", version = "1.0-SNAPSHOT" }
# --- Minecraft ---
# Lamp Command Framework
lamp-common = { group = "io.github.revxrsal", name = "lamp.common", version.ref = "lamp" }
lamp-paper = { group = "io.github.revxrsal", name = "lamp.minestom", version.ref = "lamp" }
lamp-minestom = { group = "io.github.revxrsal", name = "lamp.paper", version.ref = "lamp" }
# Kyori Adenture text shizzle
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
adventure-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventure" }
# Packetevents
packetevents = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }

# --- Config ---
sponge-yaml = { group = "org.spongepowered", name = "configurate-yaml", version = "4.2.0" }

# --- Utils ---
guava = { group = "com.google.guava", name = "guava", version = "31.1-jre" }
commons3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.17.0" }
commons-io = { group = "commons-io", name = "commons-io", version = "2.18.0" }
caffeine = { group =  "com.github.ben-manes.caffeine", name = "caffeine", version ="3.2.0" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version = "8.5.16" }

# --- Build Logic Hacks ---
build-system-license = { group = "com.github.hierynomus.license", name = "com.github.hierynomus.license.gradle.plugin", version = "0.16.1" }
build-system-license-base = { group = "com.github.hierynomus.license-base", name = "com.github.hierynomus.license-base.gradle.plugin", version = "0.16.1" }

[bundles]
minecraft = ["lamp-common", "adventure-api", "adventure-gson", "adventure-plain", "packetevents"]
utils = ["guava", "commons3", "commons-io", "caffeine", "fastutil"]
